### ISSUE TITLE
b eb melt error

### ISSUE THREAD

**Issue by FETXU** [IntellectualSites/FastAsyncVoxelSniper#72] opened 2021-09-22 09:28 UTC
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

If you try to set `/b eb` melt with arrow in hand it returns the following error, and only applies `/b e melt`

`Invalid brush parameters! Use the "info" parameter to display parameter info.`|

Please see the following image to see the difference between e and eb:
https://user-images.githubusercontent.com/6114858/78985406-fe163d00-7b28-11ea-8195-6b442f3aa91e.png

### To Reproduce

1. Join server with latest FAVS (2.2.2)
2. Hold arrow in hand
3. Use command `/b eb melt`
4. See the error shown

### Expected behaviour

The command `/b eb melt` should apply the erode brush properly to the tool

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/daa83070c03c4295b5cf9a79643374cd

### Favs Version

FAVS ver 2.2.2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

### Anything else?

Please dm me in Discord for whitlist to our server so you can test if needed :)

Fetxu#6808

**Comment by Aurelien30000** [comment] 2021-09-22 10:54
Despite the error, that's wrong, the tool is correctlty assigned. The error is caused by the blendball brush  not recognizing ``melt`` param.
Performing arrow action, blend ball brush and then erode brush are executed _(correct behavior?)_

**Comment by FETXU** [comment] 2021-09-23 09:03
Are we sure it is executing both? 

Please see the following examples:
https://imgur.com/a/Wg1E5Tn

Guess which one is the one throwing the error.


<blockquote><img src="https://i.imgur.com/V8SJnwo.jpg?fb" width="48" align="right"><div><img src="//s.imgur.com/images/favicon-16x16.png" height="14"> Imgur</div><div><strong><a href="https://imgur.com/a/Wg1E5Tn">Imgur</a></strong></div><div>Post with 0 views.</div></blockquote>

**Comment by FETXU** [comment] 2021-09-23 10:01
Quick update: I have just realised I am using FAWE 272 (due to clipboard symlinking not working)

I hope this is not a problem. 

I tried FAVS 2.0.0 (with FAWE 272) and it applies to the arrow with no error, but when using it fails to do anything and produces the following error:
https://athion.net/ISPaster/paste/view/134705b6d59e455082eb40de3209e2d1

<blockquote><div><strong><a href="https://athion.net/ISPaster/paste/view/134705b6d59e455082eb40de3209e2d1">Incendo Paste Viewer</a></strong></div></blockquote>

HOWEVER! We have tried FAVS 2.1.1(with FAWE 272) and it has NO in game errors like the original bug BUT runs like the FAVS 2.2.2 ver. In that it does something, but fails to blend the action. Please see the following result from using `/b eb melt` several times.
https://imgur.com/a/gleOQdC

**Comment by Aurelien30000** [comment] 2021-09-23 16:26
> I tried FAVS 2.0.0 (with FAWE 272) and it applies to the arrow with no error, but when using it fails to do anything and produces the following error:
Recent FAWE isn't compatible with former FAVS versions.

I had just copied old code from 1.13.2 version and it seemed to work, I will take a look.

**Comment by Aurelien30000** [comment] 2021-09-23 19:28
@FETXU Shoud blendball brush be applied after or before erode brush?

**Comment by FETXU** [comment] 2021-09-24 07:49
Hmm. Our builder say the blendball should be applied after :) @Aurelien30000

**Comment by FETXU** [comment] 2021-09-25 07:49
@Aurelien30000 We think it should be erode and then blendball. 

However, when testing the erode and blendball brushes on their own we noticed the following issues:
https://gyazo.com/3ffd7e9eeed02a4e20579fe92f62328e

This is us using /b erode and /b e smooth.

It shows that if we reset brush, then use erode it gouges out holes. Then we use e smooth and it smooths, but then back to erode and it no longer gouges, but seems to keep the e smooth behavior.

**Comment by Aurelien30000** [comment] 2021-09-25 11:04
That's partially expected, once a brush is assigned to a tool, ``/b e`` won't reassign it and just prints some info. However there is no quick command to reset preset, gonna add it while fixing the blenderode execution order ;)

**Comment by Aurelien30000** [comment] 2021-09-25 16:35
@FETXU Fix hopefully applied, can you test this and have your builder take a look? Ty!
[FastAsyncVoxelSniper-2.2.3-SNAPSHOT.zip](https://github.com/IntellectualSites/FastAsyncVoxelSniper/files/7230046/FastAsyncVoxelSniper-2.2.3-SNAPSHOT.zip)

**Comment by FETXU** [comment] 2021-09-26 08:28
@Aurelien30000 Looks good so far. Thanks mate :)

I will get our builders to properly test!

**Closed as completed** 2021-09-26 21:30 UTC
Labels: Bug
